"""init finale hebergement

Revision ID: 2ecc1a7d27c6
Revises: 
Create Date: 2025-05-24 14:49:13.749062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecc1a7d27c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hebergement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hebergement'
    )
    op.create_table('ligne_budgetaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('montant_disponible', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='hebergement'
    )
    op.create_table('demande_hebergement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('motif', sa.String(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'VALIDEE', 'REFUSEE', 'ANNULEE', 'ARCHIVEE', name='statutdemande'), nullable=True),
    sa.Column('justificatif_url', sa.String(), nullable=True),
    sa.Column('code_ligne_budgetaire', sa.String(), nullable=True),
    sa.Column('demandeur_id', sa.UUID(), nullable=False),
    sa.Column('motif_refus', sa.String(), nullable=True),
    sa.Column('prise_en_charge_validee', sa.Boolean(), nullable=True),
    sa.Column('hebergement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['hebergement_id'], ['hebergement.hebergement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hebergement'
    )
    op.create_table('invite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('demande_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('fonction', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('type_hebergement', sa.String(), nullable=True),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['hebergement.demande_hebergement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hebergement'
    )
    op.create_table('reservation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invite_id', sa.UUID(), nullable=False),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['hebergement.invite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hebergement'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation', schema='hebergement')
    op.drop_table('invite', schema='hebergement')
    op.drop_table('demande_hebergement', schema='hebergement')
    op.drop_table('ligne_budgetaire', schema='hebergement')
    op.drop_table('hebergement', schema='hebergement')
    # ### end Alembic commands ###
