"""ajout traitement demande + hebergement

Revision ID: b7e60b9fa241
Revises: c56aa7e13cf8
Create Date: 2025-04-18 16:44:59.595785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e60b9fa241'
down_revision: Union[str, None] = 'c56aa7e13cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hebergement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hebergement'
    )
    op.add_column('demande_hebergement', sa.Column('motif_refus', sa.String(), nullable=True), schema='hebergement')
    op.add_column('demande_hebergement', sa.Column('prise_en_charge_validee', sa.Boolean(), nullable=True), schema='hebergement')
    op.add_column('demande_hebergement', sa.Column('hebergement_id', sa.UUID(), nullable=True), schema='hebergement')
    op.create_foreign_key(None, 'demande_hebergement', 'hebergement', ['hebergement_id'], ['id'], source_schema='hebergement', referent_schema='hebergement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demande_hebergement', schema='hebergement', type_='foreignkey')
    op.drop_column('demande_hebergement', 'hebergement_id', schema='hebergement')
    op.drop_column('demande_hebergement', 'prise_en_charge_validee', schema='hebergement')
    op.drop_column('demande_hebergement', 'motif_refus', schema='hebergement')
    op.drop_table('hebergement', schema='hebergement')
    # ### end Alembic commands ###
