"""create table demande_hebergement

Revision ID: c56aa7e13cf8
Revises: 
Create Date: 2025-04-11 11:25:37.090785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56aa7e13cf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demande_hebergement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('motif', sa.String(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'VALIDEE', 'REFUSEE', 'ANNULEE', 'ARCHIVEE', name='statutdemande'), nullable=True),
    sa.Column('justificatif_url', sa.String(), nullable=True),
    sa.Column('code_ligne_budgetaire', sa.String(), nullable=True),
    sa.Column('demandeur_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hebergement'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demande_hebergement', schema='hebergement')
    # ### end Alembic commands ###
